// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Comment: typeof import('./src/components/common/Comment.vue')['default']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    Email: typeof import('./src/components/header/Email.vue')['default']
    Follow: typeof import('./src/components/common/follow.vue')['default']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    Info: typeof import('./src/components/header/Info.vue')['default']
    Login: typeof import('./src/components/login/Login.vue')['default']
    Main: typeof import('./src/components/main/Main.vue')['default']
    Pagination: typeof import('./src/components/pagination/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchList: typeof import('./src/components/header/SearchList.vue')['default']
    SideBar: typeof import('./src/components/main/sidebar/SideBar.vue')['default']
    Skin: typeof import('./src/components/header/Skin.vue')['default']
    UserComment: typeof import('./src/components/usercomment/UserComment.vue')['default']
  }
}
